name: benchmark1
author: author1
apiVersion: v1alpha1
stages:
  - name: candidate
    kind: candidate
    volumes:
      - name: training
        path: /input
        readonly: true
  - name: scoring
    kind: container
    image: benchmark-image
    volumes:
      - name: reference
        path: /reference
        readonly: true
volumes:
  - name: training
    type: ephemeral
  - name: reference
    type: ephemeral
