apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.worker.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: {{ .Values.worker.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: {{ .Values.worker.namespace }}
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        aadpodidbinding: worker
    spec:
      serviceAccountName: worker
      containers:
      - name: worker
        image: {{ .Values.worker.image }}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        env:
        - name: QUEUE_MODE
          value: {{ .Values.worker.queueMode }}
        - name: QUEUE_ENDPOINT
          value: {{ .Values.worker.queueEndpoint }}
        - name: AZURE_CLIENT_ID
          value: {{ .Values.identities.worker.clientId }}
        {{- if .Values.instrumentationKey }}
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: {{ .Values.instrumentationKey }}
        {{- end }}
        {{- if and .Values.identities.worker.tenantId .Values.identities.worker.clientSecret }}
        - name: AZURE_TENANT_ID
          value: {{ .Values.identities.worker.tenantId }}
        - name: AZURE_CLIENT_SECRET
          valueFrom:
              secretKeyRef:
                name: worker-identity-sp
                key: clientSecret
        {{- end }}
        {{- if .Values.worker.storage.storageClassName }}
        - name: STORAGE_CLASS_NAME
          value: {{ .Values.worker.storage.storageClassName }}
        {{- end }}
---
{{- if and .Values.identities.worker.tenantId .Values.identities.worker.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: worker-identity-sp
  namespace: worker
data:
  clientSecret: {{ .Values.identities.worker.clientSecret | b64enc }}
---
{{ else if .Values.identities.worker.resourceId }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: worker
  namespace: {{ .Values.worker.namespace }}
spec:
  azureIdentity: worker
  selector: worker
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: worker
  namespace: {{ .Values.worker.namespace }}
spec:
  type: 0
  resourceID: {{ .Values.identities.worker.resourceId }}
  clientID: {{ .Values.identities.worker.clientId }}
---
{{- end }}
{{- if .Values.worker.storage.createStorageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.worker.storage.storageClassName }}
provisioner: file.csi.azure.com
parameters:
  resourceGroup: {{ .Values.worker.storage.resourceGroup }}
  storageAccount: {{ .Values.worker.storage.storageAccount }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
{{- end }}
