# Default values for sds-worker.

argoController:
  # Set `containerRuntimeExecutor: pns` when developing on kind
  containerRuntimeExecutor: docker
  executorImage: argoproj/argoexec:v2.9.3
  image: argoproj/workflow-controller:v2.9.3
  namespace: argo

argoServer:
  # Determines whether to deploy the optional argo-server UX
  enabled: false
  image: argoproj/argocli:v2.9.3

runs:
  namespace: runs

worker:
  namespace: worker
  image: acanthamoeba/sds-worker
  queueMode: azure
  # Set the queue endpoint
  # queueEndpoint: https://<storageaccount>.queue.core.windows.net/runs

identities:
  worker: {}
    # (required) Set the clientId associated with the identity
    # clientId: 00000000-0000-0000-0000-000000000000
    
    # Set the following to use a Managed Identity on AKS
    # resourceId: /subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/worker
    
    # Set the following to use a Service Principal during development
    # tenantId: 00000000-0000-0000-0000-000000000000
    # clientSecret: 00000000-0000-0000-0000-000000000000

  benchmark: {}
    # (required) Set the clientId associated with the identity
    # clientId: 00000000-0000-0000-0000-000000000000
    
    # Set the following to use a Managed Identity on AKS
    # resourceId: /subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/worker
    
    # Set the following to use a Service Principal during development
    # tenantId: 00000000-0000-0000-0000-000000000000
    # clientSecret: 00000000-0000-0000-0000-000000000000

  candidate: {}
    # (required) Set the clientId associated with the identity
    # clientId: 00000000-0000-0000-0000-000000000000
    
    # Set the following to use a Managed Identity on AKS
    # resourceId: /subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/worker
    
    # Set the following to use a Service Principal during development
    # tenantId: 00000000-0000-0000-0000-000000000000
    # clientSecret: 00000000-0000-0000-0000-000000000000
