# Default values for sds-worker.

# instrumentationKey: <appInsights-instrumentationKey>

argoController:
  # Set `containerRuntimeExecutor: pns` when developing on kind
  containerRuntimeExecutor: docker
  executorImage: argoproj/argoexec:v2.11.0
  image: argoproj/workflow-controller:v2.11.0
  namespace: argo

argoServer:
  # Determines whether to deploy the optional argo-server UX
  enabled: false
  image: argoproj/argocli:v2.11.0

runs:
  namespace: runs

worker:
  namespace: worker
  image: acanthamoeba/sds-worker
  queueMode: azure
  # Set the queue endpoint
  # queueEndpoint: https://<queue-storageaccount>.queue.core.windows.net/runs
  # Transient storage for runs. The AKS kubelet identity will need Storage Account Contributor over this account
  storage:
    createStorageClass: true
    storageClassName: runs-transient
    # resourceGroup: <sds-resource-group>
    # storageAccount: <files-storageaccount>

identities:
  worker: {}
    # (required) Set the clientId associated with the identity
    # clientId: 00000000-0000-0000-0000-000000000000
    
    # Set the following to use a Managed Identity on AKS
    # resourceId: /subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/worker
    
    # Set the following to use a Service Principal during development
    # tenantId: 00000000-0000-0000-0000-000000000000
    # clientSecret: 00000000-0000-0000-0000-000000000000

  benchmark: {}
    # (required) Set the clientId associated with the identity
    # clientId: 00000000-0000-0000-0000-000000000000
    
    # Set the following to use a Managed Identity on AKS
    # resourceId: /subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/worker
    
    # Set the following to use a Service Principal during development
    # tenantId: 00000000-0000-0000-0000-000000000000
    # clientSecret: 00000000-0000-0000-0000-000000000000

  candidate: {}
    # (required) Set the clientId associated with the identity
    # clientId: 00000000-0000-0000-0000-000000000000
    
    # Set the following to use a Managed Identity on AKS
    # resourceId: /subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/worker
    
    # Set the following to use a Service Principal during development
    # tenantId: 00000000-0000-0000-0000-000000000000
    # clientSecret: 00000000-0000-0000-0000-000000000000
