# List benchmarks
GET {{laboratoryHost}}/benchmarks

###

# Create a benchmark
PUT {{laboratoryHost}}/benchmarks/benchmark1
Content-Type: application/json

{
  "name": "benchmark1",
  "author": "admin",
  "stages": [
    {
      "name": "candidate",
      "kind": "candidate",
      "volumes": [
        {
          "volume": "training",
          "path": "/input"
        }
      ]
    },
    {
      "name": "scoring",
      "kind": "container",
      "image": "{{laboratoryRegistry}}/alpine",
      "volumes": [
        {
          "volume": "reference",
          "path": "/reference"
        }
      ]
    }
  ]
}

###

# Get one benchmark
GET {{laboratoryHost}}/benchmarks/benchmark1

###

# Get all suites
GET {{laboratoryHost}}/suites

###

# Create a suite
PUT {{laboratoryHost}}/suites/suite1
Content-Type: application/json

{
  "name": "suite1",
  "author": "admin",
  "benchmark": "benchmark1",
  "volumes": [
    {
      "name": "training",
      "type": "AzureBlob",
      "target": "https://sample.blob.core.windows.net/training"
    },
    {
      "name": "reference",
      "type": "AzureBlob",
      "target": "https://sample.blob.core.windows.net/training"
    }
  ]
}

###

# Get one suite
GET {{laboratoryHost}}/suites/suite1

### 

# Get all candidates
GET {{laboratoryHost}}/candidates

###

# Create a candidate
PUT {{laboratoryHost}}/candidates/candidate1
Content-Type: application/json

{
  "name": "candidate1",
  "author": "admin",
  "benchmark": "benchmark1",
  "image": "{{laboratoryRegistry}}/alpine"
}

###

# Get one candidate
GET {{laboratoryHost}}/candidates/candidate1

###

# Get all runs
GET {{laboratoryHost}}/runs

###

# @name createRun
# Create a run
POST {{laboratoryHost}}/runs
Content-Type: application/json

{
  "candidate": "candidate1",
  "suite": "suite1"
}

###

@runName = {{createRun.response.body.$.name}}

# Get one run
GET {{laboratoryHost}}/runs/{{runName}}

###

# Update run status
PATCH {{laboratoryHost}}/runs/{{runName}}
Content-Type: application/json

{
  "status": "running"
}

###

# Report run results
POST {{laboratoryHost}}/runs/{{runName}}/results
Content-Type: application/json

{
  "measures": {
    "passed": 5,
    "failed": 6
  }
}

###

# Get run results
GET {{laboratoryHost}}/runs?benchmark=benchmark1&suite=suite1
