name: catdetection
author: acanthamoeba
apiVersion: v1alpha1
stages:
- name: prep
  kind: container
  image: acanthamoeba/sds-prep
  volumes:
  - name: images
    path: /out
    readonly: false

- name: candidate
  kind: candidate
  volumes:
  - name: images
    path: /in
    readonly: true
  - name: predictions
    path: /out
    readonly: false

- name: eval
  kind: container
  image: acanthamoeba/sds-eval
  volumes:
  - name: predictions
    path: /results
    readonly: true
  - name: scores
    path: /scores
    readonly: false

